### ISSUE TITLE
micropython stepper on ESP32 PINS GPIO27 AND GPIO14 can't be used?

### ISSUE THREAD

**Issue by AOkba** [redoxcode/micropython-stepper#1]
Why MICROPYTHON STEPPER ON ESP32: 
GPIO27 AND GPIO14 CAN'T BE USED?

**Comment by redoxcode** [comment]
Hey AOkba,
I can't see any reason at the moment why GPIO27 and GPIO14 shouldn't work...
Can you provide some more detail on this issue?

1. Do other GPIO pins work for you?
2. Can you share the code you are using? (Maybe something is messing with the timers :thinking:)
3. Can you share the circuit you are using?

Thank you

**Comment by AOkba** [comment]
Thank you.
Cheers.
Tested: MicroPython on ESP32
All good 
 
import time
import machine 
from stepper import Stepper

'''
ESP32
'''
#s1 = Stepper(12,13,steps_per_rev=200,speed_sps=100)  # ok
s1 = Stepper(27,14,steps_per_rev=200,speed_sps=100) # Ok
#s1 = Stepper(32,33,steps_per_rev=200,speed_sps=100) # Ok   


s1.target_deg(90)
time.sleep(5.0)
s1.target_deg(0)
time.sleep(5.0)
