### ISSUE TITLE
Can't use 2 steppers at the same time

### ISSUE THREAD

**Issue by Sylvain-BROCAS** [redoxcode/micropython-stepper#2]
Hi,
It is said in your read me that this lib allows the user to command several steppers in a non blocking way.
I understand here that 2 steppers can be driven independantly at the same time.

I tried a simple wiring, with 2 stepper using 2 TMC2209drivers. with the code under this issue. I tried to disconnect motors 1 after the other to test it alone and everything is going well, it does 180° in one direction then comes back to 0°. But when I plug both motors, only one is moving.
The non moving stepper is plugged to a driver that seems to have a default (high urrent consumption when the motor isn't enabled). However, this particular driver is moving when I command it alone.

Do you have an idea of what would cause this behavior ?

thanks,
Sylvain

My program :
```Python
from stepper import Stepper
import time
from machine import Pin

Pin(5, Pin.OUT).off()
Pin(21, Pin.OUT).off()


s1 = Stepper(18,19,steps_per_rev=200*8, speed_sps=500, en_pin=21, timer_id=-1)
s2 = Stepper(22,23,steps_per_rev=200*8, speed_sps=500, en_pin=5, timer_id=-1)

s1.target_deg(0)
s2.target_deg(0)
print(1)
time.sleep(3.0)
s1.target_deg(180)
s2.target_deg(180)
time.sleep(3.0)
print(2)
s1.target_deg(0)
s2.target_deg(0)
```

**Comment by redoxcode** [comment]
Hi Sylvain,
yes, this library can drive multiple steppers at the same time.
Your code looks fine to me. What microcontroller are you using?
Maybe you have access to an Oscilloscope and can check if the outputs of the microcontroller are as expected.

If you use that code and connect one stepper to pins 18,19,21 it is working?
If you use that code and connect the same stepper to pins 22,23,5 it is working as well?
If both of the above are true, there is an issue with your hardware. Maybe your power supply isn't strong enough or one of your stepper drivers is broken.

**Comment by Sylvain-BROCAS** [comment]
I use an ESP32 devkit V1 running with micropython 1.20.

I will try with the code containing s1 and s2 and try to plug one motor after another.
I have new TMC2209 drivers incoming, I will try with it when it will b delivered.

Thank you

**Comment by Sylvain-BROCAS** [comment]
Hi,
I was wondering if your lib includes a tool to know when the target reached.
Do you have a function or should I use a "while not reached "

Thank you

**Comment by redoxcode** [comment]
Hey, sorry for the late reply. Kinda busy these days...
Yeah, now that you mention it I guess there should be an easier way to check that.
Currently you can either check if the current position is your target position or calculate the time it should take based on the speed...
I will try to add a better way to do that soon (tm).

**Comment by redoxcode** [comment]
BTW: Did you get the 2 steppers to work?

**Comment by balbert1** [comment]
I'm having the same issue with trying to use two steppers at once. I've found that whichever stepper I declare first will work for me, but the other will remain stationary. I double checked the motors and they will all work independently but not when I try to use them both at once. 

Here is my code on a portenta H7 with MP6500 drivers. In this case only stepper 1 will spin, but if I comment out stepper 1, stepper 2 works fine:

```
from machine import Pin
import time
from stepper import Stepper

s1 = Stepper('PG7','PE3', steps_per_rev=3200,speed_sps=1000)
s2 = Stepper('PC7','PD5', steps_per_rev=3200,speed_sps=1000)

s1.target(3200)
s2.target(3200)
```

EDIT: This seems to be an issue of setting the virtual timer on the Portenta H7. It could be the same for any STM32 boards. The same Library works for multiple motors with a Raspberry Pi Pico. Got it to work with multiple motors if the timers are declared using pyb instead of machine. 

Added:
`import pyb`

In _init_ changed from machine to pyb for self.timer:
`self.timer = pyb.Timer(timer_id)`

In the main script added `timer_id=1`, `timer_id=2`, etc. for each motor when calling Stepper.

**Comment by Sylvain-BROCAS** [comment]
> I'm having the same issue with trying to use two steppers at once. I've found that whichever stepper I declare first will work for me, but the other will remain stationary. I double checked the motors and they will all work independently but not when I try to use them both at once.
> 
> Here is my code on a portenta H7 with MP6500 drivers. In this case only stepper 1 will spin, but if I comment out stepper 1, stepper 2 works fine:
> 
> ```
> from machine import Pin
> import time
> from stepper import Stepper
> 
> s1 = Stepper('PG7','PE3', steps_per_rev=3200,speed_sps=1000)
> s2 = Stepper('PC7','PD5', steps_per_rev=3200,speed_sps=1000)
> 
> s1.target(3200)
> s2.target(3200)
> ```
> 
> EDIT: This seems to be an issue of setting the virtual timer on the Portenta H7. It could be the same for any STM32 boards. The same Library works for multiple motors with a Raspberry Pi Pico. Got it to work with multiple motors if the timers are declared using pyb instead of machine.
> 
> Added: `import pyb`
> 
> In _init_ changed from machine to pyb for self.timer: `self.timer = pyb.Timer(timer_id)`
> 
> In the main script added `timer_id=1`, `timer_id=2`, etc. for each motor when calling Stepper.

Hi, 
I forgot to share this here but I found the same solution. Changing the timer IDs by 1 and 2 gives the waited result

**Comment by redoxcode** [comment]
Glad you figured it out! I was suspecting the timer to be the issue. Sadly I don't have that many different boards to test the library on. Mostly rp2040 ones.
I need to improve the documentation and highlight that a timer_id is needed for some boards.

@balbert1 :
Could you verify that the change from _machine_ to _pyb_ is indeed necessary?
It would make things more complicated if some boards need _pyb_ and some boards _machine_ ...
Thank you!

**Comment by Sylvain-BROCAS** [comment]
I didn't have to to add pyb personnaly so it doesn't seem to be necessary for all boards.
